startPage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

contact:
    path: /kontakt
    defaults: { _controller: AppBundle:Default:contact }

sport:
    path: /sport/{discipline}/{state}
    defaults:
        _controller: AppBundle:Sport:index
        state: null