startPage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

contact:
    path: /kontakt
    defaults: { _controller: AppBundle:Default:contact }

sport:
    path: /sport/{discipline}
    defaults:
        _controller: AppBundle:Sport:index
        state: null
        page: null

sport_state:
    path: /sport/{discipline}/wojewodztwo/{state}
    defaults:
        _controller: AppBundle:Sport:index
        state: null
        page: null
sport_page:
    path: /sport/{discipline}/strona/{page}
    defaults:
        _controller: AppBundle:Sport:index
        state: null
        page: null